"""Public API for humanist_core.hacp (HACP sidecar SDK)."""

from .builders import (
    EnvelopeBuilder,
    TokenBuilder,
    SignedIntentEnvelope,
    SignedDecisionToken,
)
from .client import SidecarClient
from .models import (
    IntentEnvelope,
    DecisionToken,
    Scope,
    AutonomyBudget,
    ProposedAction,
    Constraints,
)
from .exceptions import (
    HACPError,
    SchemaValidationError,
    SignatureFailureError,
    KeyRevokedError,
    EnvelopeRevokedError,
    TokenRevokedError,
    EnvelopeExpiredError,
    TokenExpiredError,
    ScopeExceededError,
    BoundaryCrossingError,
    BudgetExhaustedError,
    TraceabilityFailureError,
    CheckpointRequiredError,
    ReauthorizeRequiredError,
    parse_reason_code,
)
from .crypto import (
    generate_keypair,
    load_private_key_pem,
    export_private_key_pem,
    sign,
    verify,
    b64url_encode,
    b64url_decode,
    canonicalize_json,
    hash_action,
)

__all__ = [
    "EnvelopeBuilder",
    "TokenBuilder",
    "SignedIntentEnvelope",
    "SignedDecisionToken",
    "SidecarClient",
    "IntentEnvelope",
    "DecisionToken",
    "Scope",
    "AutonomyBudget",
    "ProposedAction",
    "Constraints",
    "HACPError",
    "SchemaValidationError",
    "SignatureFailureError",
    "KeyRevokedError",
    "EnvelopeRevokedError",
    "TokenRevokedError",
    "EnvelopeExpiredError",
    "TokenExpiredError",
    "ScopeExceededError",
    "BoundaryCrossingError",
    "BudgetExhaustedError",
    "TraceabilityFailureError",
    "CheckpointRequiredError",
    "ReauthorizeRequiredError",
    "parse_reason_code",
    "generate_keypair",
    "load_private_key_pem",
    "export_private_key_pem",
    "sign",
    "verify",
    "b64url_encode",
    "b64url_decode",
    "canonicalize_json",
    "hash_action",
]